---
- name: Deploy RideReady Application
  hosts: all
  
  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ playbook_dir }}/docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d
      
