apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: RideReady-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: chakradhar63/backend-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
        env: 
        - name: MONGO
          valueFrom:
            secretKeyRef:
              name: RideReady-backend-secret
              key: MONGO
        - name: JWT
          valueFrom:
            secretKeyRef:
              name: RideReady-backend-secret
              key: JWT

